<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use RuntimeException;

/**
 * Sends transactional emails via the Brevo v3 API.
 *
 * Uses the HTTP transactional endpoint (not SMTP) so we get a messageId
 * back immediately for tracking delivery events via webhooks.
 *
 * @see https://developers.brevo.com/reference/sendtransacemail
 */
class BrevoEmailService
{
    private const API_URL = 'https://api.brevo.com/v3/smtp/email';

    /**
     * Send a single transactional email.
     *
     * @param  string       $toEmail
     * @param  string|null  $toName
     * @param  string       $subject
     * @param  string       $htmlContent     HTML body
     * @param  string|null  $textContent     Plain-text fallback (auto-generated by Brevo if null)
     * @param  array|null   $sender          ['name' => ..., 'email' => ...] overrides config defaults
     * @param  array|null   $replyTo         ['name' => ..., 'email' => ...]
     * @param  array        $tags            Up to 10 tags for categorization
     * @param  array        $headers         Custom X-headers (e.g. X-Campaign-Id)
     * @return array{messageId: string, raw: array}
     *
     * @throws RuntimeException on any failure
     */
    public function send(
        string  $toEmail,
        ?string $toName = null,
        string  $subject = '',
        string  $htmlContent = '',
        ?string $textContent = null,
        ?array  $sender = null,
        ?array  $replyTo = null,
        array   $tags = [],
        array   $headers = [],
    ): array {
        $apiKey = config('brevo.api_key');

        if (!$apiKey) {
            throw new RuntimeException('Brevo API key not configured (BREVO_API_KEY).');
        }

        $payload = [
            'sender'  => $sender ?? [
                'name'  => config('brevo.sender_name'),
                'email' => config('brevo.sender_email'),
            ],
            'to' => [
                [
                    'email' => $toEmail,
                    'name'  => $toName ?? $toEmail,
                ],
            ],
            'subject'     => $subject,
            'htmlContent' => $htmlContent,
        ];

        if ($textContent) {
            $payload['textContent'] = $textContent;
        }

        // Reply-to
        $replyToEmail = $replyTo['email'] ?? config('brevo.reply_to_email');
        if ($replyToEmail) {
            $payload['replyTo'] = [
                'email' => $replyToEmail,
                'name'  => $replyTo['name'] ?? config('brevo.reply_to_name') ?? config('brevo.sender_name'),
            ];
        }

        if (!empty($tags)) {
            $payload['tags'] = array_slice($tags, 0, 10);
        }

        if (!empty($headers)) {
            $payload['headers'] = $headers;
        }

        Log::debug('BrevoEmailService: sending email', [
            'to'      => $toEmail,
            'subject' => $subject,
            'tags'    => $tags,
        ]);

        $response = Http::withHeaders([
            'api-key'      => $apiKey,
            'Content-Type' => 'application/json',
            'Accept'       => 'application/json',
        ])->timeout(30)->post(self::API_URL, $payload);

        if ($response->failed()) {
            $body = $response->json();
            $error = $body['message'] ?? $body['error'] ?? $response->body();

            Log::error('BrevoEmailService: send failed', [
                'to'     => $toEmail,
                'status' => $response->status(),
                'error'  => $error,
            ]);

            throw new RuntimeException(
                "Brevo API error ({$response->status()}): {$error}"
            );
        }

        $data = $response->json();
        $messageId = $data['messageId'] ?? ($data['messageIds'][0] ?? null);

        if (!$messageId) {
            Log::warning('BrevoEmailService: no messageId in response', [
                'to'       => $toEmail,
                'response' => $data,
            ]);
        }

        Log::info('BrevoEmailService: email sent', [
            'to'        => $toEmail,
            'messageId' => $messageId,
        ]);

        return [
            'messageId' => $messageId ?? '',
            'raw'       => $data,
        ];
    }

    /**
     * Convert plain text body to minimal HTML (preserves line breaks).
     */
    public static function textToHtml(string $text): string
    {
        $escaped = htmlspecialchars($text, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $withBreaks = nl2br($escaped);

        return <<<HTML
        <!DOCTYPE html>
        <html>
        <head><meta charset="utf-8"></head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 15px; line-height: 1.6; color: #1a1a1a; max-width: 600px; margin: 0 auto; padding: 20px;">
        {$withBreaks}
        </body>
        </html>
        HTML;
    }
}
